### ISSUE TITLE
Feature Request: exclude `_test.go` files by default

### ISSUE THREAD

**Issue by scottmmjackson** [natdm/typewriter#10]
Golang [canon](https://golang.org/pkg/testing/) suggests the use of a `_test.go` naming convention  for test files. Most users probably don't care about strong types for their testing mocks.

If one were to integrate `typewriter` into their build pipeline, this could make it easier to feed it an entire project directory and get a reasonably sized typing file back. This behavior could be switched off by something like `-include-tests` on the command line.

**Comment by natdm** [comment]
Another good request! This should be relatively easy.

**Comment by scottmmjackson** [comment]
It looks like it's somewhat aware of this: https://github.com/natdm/typewriter/blob/master/parse/parse.go#L49

**Comment by natdm** [comment]
Correct, but the idea that sticks out is that it could be optional. I'm not aware of the cases where someone would need to mock something in their `_test` files, but I've seen things pop up that are stranger than that.
