### ISSUE TITLE
Doesn't handle `-` character in JSON tag properly

### ISSUE THREAD

**Issue by scottmmjackson** [natdm/typewriter#9]
While it's not recommended to use kebab-case in JS property names, it's entirely valid to do so.

The generator ends up generating invalid types by refusing to quote the property names when to do otherwise would be invalid.

**Example**

```
type MyInvalidJsType struct {
   someProperty string `json:"some-property"` // wow, why did we do this? totally valid JS though
}
```

**Expected**
```
export type MyInvalidJsType = {
  "some-property": string,
}
```

**Actual**
```
export type MyInvalidJsType = {
  some-property: string, // unexpected token `-`
}
```

**Comment by natdm** [comment]
Good find. I will add a test-case and work on this. Thank you for the write-up!

**Comment by scottmmjackson** [comment]
`/` also appears to be a valid in a quoted property name.

It might be that you're going to have to make a `validNonQuotedIdentifier` tester or something. I think I remember where that part of the ecma spec is...

http://es5.github.io/x7.html#x7.6

Bad news: there's a lot of crazy rules in there.

It's probably not handling reserved words like "break" either.

**Comment by scottmmjackson** [comment]
Oh my, this makes me cry.

https://mathiasbynens.be/demo/javascript-identifier-regex

Beware, I've already noticed that the ES6 regex is missing ES7's "async" keyword despite having "await"

**Comment by natdm** [comment]
I can't seem to reproduce this. I put in your exact example and I get:
```javascript
export type MyInvalidJsType = { 
	some-property: string// wow, why did we do this? totally valid JS though
}
```

are you sure you're up to date with master?

**Comment by scottmmjackson** [comment]
That's reproduced accurately. Hyphens aren't legal identifier characters in
ECMAScript, so the result you gave yields a parse error. The expected
result is a quoted property name, e.g.:

```
export type MyInvalidJsType = {
    "some-property": string
}
```

comments excluded for readability.

**Comment by natdm** [comment]
Ok, I understand fully now. Thanks for the assistance.

**Comment by natdm** [comment]
@scottmmjackson -- https://github.com/natdm/typewriter/pull/11 This should fix it.

**Comment by natdm** [comment]
Done
